name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js "${{ matrix.node-version }}"
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.14
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          path: "${{ steps.pnpm-cache.outputs.STORE_PATH }}"
          restore-keys: |
            "${{ runner.os }}-pnpm-store-"

      - name: Install dependencies
        run: pnpm install

      - name: Build production bundle
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # ビルドされたコンテンツのディレクトリを指定
